# Copyright 2022 Rafe Kaplan
# SPDX-License-Identifier: Apache-2.0
#
# Created: 2022-06-06
# Updated: 2022-06-09

- id: conhead
  name: conhead
  description: Ensure that source files have consistent headers.
  entry: conhead
  language: python
