repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [
        ]
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [
          --branch, main
        ]
      - id: trailing-whitespace

  - repo: local
    hooks:

      - id: sort-imports
        name: sort python imports
        language: system
        entry: poetry run isort
        types: [python]

      - id: format
        name: format python
        language: system
        entry: poetry run black
        types: [python]

      - id: lint
        name: lint
        language: system
        entry: poetry run flake8
        types: [python]

      - id: type-check
        name: type check
        language: system
        entry: poetry run pyright
        types: [python]

      - id: test
        name: tests
        language: system
        entry: poetry run pytest
        types: [python]
        pass_filenames: false
