# Copyright 2022 Rafe Kaplan
# SPDX-License-Identifier: Apache-2.0
#
# Updated: 2022-05-30

- id: conhead
  name: conhead
  description: Ensure that source files have consistent headers.
  entry: conhead
  language: python
