name: Release Python package

on:
  push:
    tags:
      - 'v*'

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    name: Builds and publishes release.
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        architecture: x64

    - name: Install Poetry
      run: pipx install --python python${{ matrix.python-version }} poetry

    - name: Extract version from poetry
      run: mkdir dist && poetry install --dry-run | grep -o 'conhead \(.*\)' | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*' > dist/VERSION

    - name: Make sure version matches GITHUB_REF
      run: test "refs/tags/v$(cat dist/VERSION)" == "$GITHUB_REF"

    - name: Build sdist
      run: poetry build -f sdist

    - name: Create test installation environment
      run: python -m venv dist/test-installation

    - name: Test package installs into environment
      run: dist/test-installation/bin/pip install dist/conhead-$(cat dist/VERSION).tar.gz
