# Copyright 2022 Rafe Kaplan
# SPDX-License-Identifier: Apache-2.0
#
name: Test

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-20.04
    name: Check things
    steps:

    - uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry

    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        architecture: x64
        cache: poetry

    - name: Extract version from poetry
      run: >
        mkdir dist &&
        poetry install --dry-run |
        grep -o 'conhead \(.*\)' |
        grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*' > dist/VERSION

    - name: Put version in environment
      run: echo "release_version=$(cat dist/VERSION)" >> $GITHUB_ENV

    - name: Check
      run: echo ${{ env.release_version }}

    - name: What is github env
      run: echo "$GITHUB_ENV"
