# Copyright 2022 Rafe Kaplan
# SPDX-License-Identifier: Apache-2.0
#
name: Testing workflow

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    name: Do test
    steps:

      - id: a
        run: echo "::set-output name=xyz::blarg"

      - run: echo ${{ steps.a.outputs.xyz }}
